# .goreleaser.yaml
project_name: srn-coreutils
version: 2
builds:
  - id: srn
    main: ./
    binary: srn
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: infraflakes
    name: srn-coreutils
